theme: minima
title: Guitar In Theory
author: Brandon Sibilia
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  We discuss how to play and tune guitars. We go through the different types and discuss diffenet players and bands who play.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
